# Generated by Django 4.2.11 on 2024-03-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('serial_number', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('product_name', models.CharField(default=None, max_length=200)),
                ('product_desc', models.CharField(default=None, max_length=2000)),
                ('manufacturer_info', models.CharField(default=None, max_length=500)),
                ('warranty_info', models.CharField(max_length=200, null=True)),
                ('date_of_manufacture', models.DateField(default=None)),
            ],
        ),
    ]
